### ISSUE TITLE
LLVM build error on Alpine Linux x86

### ISSUE THREAD

**Issue by orhun** [ndd7xv/heh#126]
**Describe the bug**
I'm the maintainer of `heh` for Alpine Linux, and hit a very weird build issue while building `0.5.0`:

```
   Compiling heh v0.5.0 (/builds/orhun/aports/testing/heh/src/heh-0.5.0)
LLVM ERROR: Cannot emit physreg copy instruction
error: could not compile `heh` (bin "heh")
```

P.S. never seen such an error in my life 😳 

**To Reproduce**
The issue is reproducible on Alpine Linux x86, see the logs here: https://gitlab.alpinelinux.org/orhun/aports/-/jobs/1337171

**Expected behavior**
Successful build.

**Desktop (please complete the following information):**
- Alpine Linux

**Additional context**
- https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/63816

**Comment by ndd7xv** [comment]
I, too, have never seen this in my life 😳 just given the message I wonder if this is beyond my repo since it seems like an error with LLVM and it would be strange that any sort of Rust code would be compiled down to IR that can't be emitted. I don't know too much about Rust/LLVM internals though, so I can say anything with confidence...

**Comment by orhun** [comment]
Yeah, I feel like this is a [heisenbug](https://en.wikipedia.org/wiki/Heisenbug), but let's see.
