### ISSUE TITLE
Add sample data

### ISSUE THREAD

**Issue by nag763** [ndd7xv/heh#8]
Hello, 

When I ran in your repo few days ago, I wanted to try the tool but realized there was no sample data anywhere that could help me to test your tool.

Since I had no data to test the tool on either, I couldn't test.

Maybe it would be a good idea to add sample data for people that just want to have a look on your project ? :smile:

**Comment by ndd7xv** [comment]
Hi, and thanks for the issue! :smile: 

Could you elaborate on what sort of sample data you're looking for? As a hex editor, heh can inspect the bytes of any file that you have permission can read and write to - images, text files, binaries/executables, you name it.

As a part of https://github.com/ndd7xv/heh/issues/4, I'll add examples of how to run the command, especially when there are more options. For now, it's only `heh path/to/file` - so, for example, if you clone this repo, you could run `cargo r -- demo.png`. If you have heh installed already, you could run `heh <path_to_repo>/demo.png` to inspect the bytes of the image used in the README.  

I'm not entirely sure if I should add sample data, since a user should be able to specify nearly any file on their system (as well as any file in this repo) and inspect its bytes.

**Comment by nag763** [comment]
hello @ndd7xv ,
My apologies, I believe it was some sort of Hex dump reader, but that was the usage I had in mind, not the primary one ahah.
Thanks for that precision. :smile:
